#!/bin/sh

if [ -f config.status ]; then
  make maintainer-clean
fi

./bootstrap && \
    ./configure \
  --prefix=/usr \
  --mandir=/usr/share/man \
  --localstatedir=/var \
  --sysconfdir=/etc \
  --enable-arfailure=builtin \
  --enable-openconnect=builtin \
  --enable-openvpn=builtin \
  --enable-vpnc=builtin \
  --enable-session-policy-local=builtin \
  --enable-nmcompat \
  --enable-polkit $*
